[agent]
  interval = "5s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "5s"
  flush_jitter = "0s"
  precision = "1s"
  hostname = "telegraf-iot"
  omit_hostname = true

# ===================================================================
# ENTRADA: Suscripción al Broker MQTT
# ===================================================================
[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto:1883"]

  # Ejemplo de tópico: healthwatch/patient_id/device_id/biometrics
  topics = [
    "healthwatch/+/+/biometrics",
  ]
  
  topic_tag = "topic"
  data_format = "json"
  name_override = "biometrics"

  json_string_fields = ["id_patient", "id_device"]
  tag_keys = ["id_patient", "id_device"]

# ===================================================================
# SALIDA: Escritura en InfluxDB 3 Core
# ===================================================================
[[outputs.influxdb_v3]]
  urls = ["http://influxdb3-core:8181"]
  token = "${INFLUXDB3_AUTH_TOKEN}"
  database = "${INFLUXDB3_DATABASE_NAME}"